export const apiConfig = {
  baseAPIUrl: `/api/v1`,
  auth: {
    google: "/google-auth",
    sendOtp: "/send-otp",
    loginOtp: "/login-Otp",
    verifyOtp: "/verify-otp",
    verifyLoginOtp: "/verify-loginotp",
    logout: "/logout",

    adminLogin: "/admin/login",
    adminRegister: "/admin/register",
    accessToken: "/new/access-token",
    forgotPassword: "/admin/forgot-password",
    verifyForgotOtp: "/admin/verify-password",
    updatePassword: "/admin/update-password",

    userLogins: "/access/login",
    userRegister: "/access/register",
    checkUserExistence: "/user/present",
    createNewUser: "/user/new",
    getUserInfoById: "/user/:id",
  },
  admin: {
    adminApproveOrganization: "/approve/organization/:id",
    adminApproveKitchen: "/approve/kitchen/:id",
  },
  kitchens: {
    newkitchens: "/new",
    updatekitchens: "/update/:id",
    deletekitchens: "/delete/:kitchenId",
    getAllkitchens: "/all",
    getkitchensById: "/:kitchenId",
    toggleKitchensStatus: "/status/:id",
    handleGetUserApprovedKitchens: "/user/approved",

    createCategory: "/categories",
    getallCategories: "/categories/all",
    updateCategory: "/categories/:id",
    deleteCategory: "/categories/:id",
    toggleCategoryStatus: "/categories/:id/toggle-status",

    getallSubCategories: "/subcategories/all",
    createSubcategory: "/subcategories",
    getSubcategoriesByCategory: "/categories/:categoryId/subcategories",
    getSubcategoryById: "/subcategories/:id",
    updateSubcategory: "/subcategories/:id",
    deleteSubcategory: "/subcategories/:id",
    toggleSubcategoryStatus: "/subcategories/:id/toggle-status",
    getUnapprovedKitchens: "/requested/all",
  },
  menu: {
    createCategory: "/categories",
    getAllCategories: "/categories",
    updateCategory: "/categories/:id",
    deleteCategory: "/categories/:id",
    toggleCategoryStatus: "/categories/:id/toggle-status",

    getAllSubCategories: "/subcategories",
    getAllCategoriesByStatus: "/category/status",
    createSubcategory: "/subcategories",
    getSubcategoriesByCategory: "/categories/:categoryId/subcategories",
    getSubcategoryById: "/subcategories/:id",
    updateSubcategory: "/subcategories/:id",
    deleteSubcategory: "/subcategories/:id",
    toggleSubcategoryStatus: "/subcategories/:id/toggle-status",

    createItem: "/allmenuitems",
    getItemById: "/allmenuitems/:id",
    listItems: "/allmenuitems",
    updateItem: "/allmenuitems/:id",
    deleteItem: "/allmenuitems/:id",
    changeItemStatus: "/allmenuitems/:id/status",
    getMenuItemsByKitchen: "/kitchen/:kitchenId",
  },
  organization: {
    newOrganization: "/new",
    updateOrganization: "/update/:id",
    deleteOrganization: "/delete/:orgId",
    getAllOrganization: "/all",
    getOrganizationById: "/:orgId",
    toggleOrganizationStatus: "/status/:id",
    handleGetUserOrganizations: "/user/get-all",

    createCategory: "/categories",
    getAllCategories: "/categories/all",
    updateCategory: "/categories/:id",
    deleteCategory: "/categories/:id",
    toggleCategoryStatus: "/categories/:id/toggle-status",

    getAllSubCategories: "/subcategories/all",
    createSubcategory: "/subcategories",
    getSubcategoriesByCategory: "/categories/:categoryId/subcategories",
    getSubcategoryById: "/subcategories/:id",
    updateSubcategory: "/subcategories/:id",
    deleteSubcategory: "/subcategories/:id",
    toggleSubcategoryStatus: "/subcategories/:id/toggle-status",
    getAllCategoriesByStatus: "/category/status",

    getUnapprovedOrganisations: "/requested/all",
    approveOrganization: "/approve/:id",
  },
  collab: {
    collaborateKitchen: "/select",
    listCollaboratedKitchens: "/organization/:organization_id",
    getAllColloborations: "/all",
    getCollaborationById: "/:id",
    addCollaboration: "/request/add-new-collab",
    getCollaborationDetails: "/get-collaboration-details",
  },
  designation: {
    createDesignation: "/designations",
    getAllDesignations: "/designations/all",
    getDesignationById: "/designations/:id",
    updateDesignation: "/designations/:id",
    deleteDesignation: "/designations/:id",
    toggleDesignationStatus: "/designations/:id/toggle-status",

    newRoleAndAccess: "/new",
    getRoleAndAccess: "/",
    getRoleAndAccessById: "/:roleId",
  },
  employee: {
    createEmployee: "/employees",
    getAllEmployees: "/employees/all",
    getEmployeeById: "/employees/:id",
    updateEmployee: "/employees/:id",
    deleteEmployee: "/employees/:id",
    toggleEmployeeStatus: "/employees/:id/toggle-status",
  },
  kitchenEmployee: {
    createEmployee: "/employees",
    getAllEmployees: "/employees-all/:kitchenId",
    getEmployeeById: "/employees/:id",
    updateEmployee: "/employees/:id",
    deleteEmployee: "/employees/:id",
    toggleEmployeeStatus: "/employees/:id/toggle-status",
  },
  orgemployee: {
    createOrgEmployee: "/orgemployee",
    getAllEmployeesOfOrg: "/orgemployee/all/:id",
    getOrgEmployeeById: "/orgemployee/:id",
    updateOrgEmployee: "/orgemployee/:id",
    deleteOrgEmployee: "/orgemployee/:id",
    toggleOrgEmployeeStatus: "/orgemployee/:id/toggle-status",
    getEmployeesOrg: "/employee/org",
    newDesignation: "/employee/new-designation",
    getDesignation: "/employee/designations",
    getRoleAndAccessById: "/employee/role-accesss/:roleId",
  },
  addressDetails: {
    getAllCountries: "/allcountries",
    getStatesByCountry: "/states/:countryName",
    getCitiesByState: "/cities/:stateName",
    getDistrictsByState: "/districts/:stateId",
  },

  kitchenMenu: {
    getKitchenMenu: "/kitchen-menu/:kitchenId",
    createkitchenMenu: "/kitchen-menu/:id",
    getkitchenMenuItemDetail: "/:kitchenId/menu-item/:itemId",
    removekitchenMenu: "/kitchen-menu/:kitchen_id/remove/:item_id",
    updateKitchenMenu: "/:kitchenId/menu-item/:itemId",
    deleteSubcategory: "/kitchen-menu/subcategories/:id",
    toggleSubcategoryStatus: "/kitchen-menu/subcategories/:id/toggle-status",
  },
  notification: {
    getUserNotifications: "/get/:userId",
    getNotificationById: "/get/:notificationId",
    getAllNotifications: "/all",
  },
};
